### ISSUE TITLE
Error updating from 0.1.0 to 0.2.0

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/ipython_genutils-feedstock#6]
I get an error updating ipython genutils from 0.1.0 to 0.2.0. Below is the update message I got.

```
Fetching package metadata .................
Solving package specifications: ..........
Warning: 2 possible package resolutions (only showing differing packages):
  - bioconda::bleach-1.4.2-py27_0.tar.bz2, conda-forge::html5lib-0.999999999-py27_0.tar.bz2
  - conda-forge::bleach-1.5.0-py27_0.tar.bz2, conda-forge::html5lib-0.999-py27_0.tar.bz2

Package plan for installation in environment /home/max/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boto-2.46.1                |           py27_0         1.4 MB
    ipython_genutils-0.2.0     |           py27_0          35 KB  conda-forge
    pyasn1-0.2.3               |           py27_0          76 KB  conda-forge
    traitlets-4.3.2            |           py27_0         126 KB  conda-forge
    pytest-3.0.7               |           py27_0         259 KB  conda-forge
    conda-build-2.1.6          |           py27_0         307 KB  conda-forge
    jupyterlab-0.17.5          |           py27_0         3.1 MB  conda-forge
    jupyter_highlight_selected_word-0.0.8|           py27_0          11 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.2 MB

The following packages will be UPDATED:

    boto:                            2.45.0-py27_0             --> 2.46.1-py27_0            
    conda-build:                     2.1.4-py27_1  conda-forge --> 2.1.6-py27_0  conda-forge
    ipython_genutils:                0.1.0-py27_0  conda-forge --> 0.2.0-py27_0  conda-forge
    jupyter_highlight_selected_word: 0.0.7-py27_0  conda-forge --> 0.0.8-py27_0  conda-forge
    jupyterlab:                      0.17.4-py27_0 conda-forge --> 0.17.5-py27_0 conda-forge
    pyasn1:                          0.2.2-py27_0  conda-forge --> 0.2.3-py27_0  conda-forge
    pytest:                          3.0.6-py27_0  conda-forge --> 3.0.7-py27_0  conda-forge
    traitlets:                       4.3.1-py27_0  conda-forge --> 4.3.2-py27_0  conda-forge

Proceed ([y]/n)? y 

Fetching packages ...
boto-2.46.1-py 100% |################################| Time: 0:00:00   2.67 MB/s
ipython_genuti 100% |################################| Time: 0:00:00 193.64 kB/s
pyasn1-0.2.3-p 100% |################################| Time: 0:00:00 262.47 kB/s
traitlets-4.3. 100% |################################| Time: 0:00:00 284.59 kB/s
pytest-3.0.7-p 100% |################################| Time: 0:00:00 462.74 kB/s
conda-build-2. 100% |################################| Time: 0:00:00 429.43 kB/s
jupyterlab-0.1 100% |################################| Time: 0:00:02   1.52 MB/s
jupyter_highli 100% |################################| Time: 0:00:00   9.94 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/max/anaconda2/lib/python2.7/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 22, in <module>
    from ._compat.nbextensions import (
  File "/home/max/anaconda2/lib/python2.7/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 27, in <module>
    from ipython_genutils.path import ensure_dir_exists
ImportError: No module named ipython_genutils.path
```

**Comment by jakirkham** [comment]
Picked an arbitrary package and it does seem to be there. Could you please provide us OS and arch?

**Comment by jakirkham** [comment]
Checked `linux-64` in case that is relevant and it also has `ipython_genutils.path`.

**Comment by kain88-de** [comment]
Fedora 25, x64, Python 2.7.

**Comment by jakirkham** [comment]
Strange. It is definitely in the conda package for that platform. Maybe worth trying to purge any weird lingering broken packages and do a fresh install. To that end could you please try the commands below?

```
conda remove -y --force ipython_genutils
conda clean -tipsy
conda install -y ipython_genutils
```

**Comment by kain88-de** [comment]
Now the package installs without error.

**Comment by jakirkham** [comment]
Thanks @kain88-de.
